"use client";
import {useEffect,useState} from "react";import {useParams,useRouter} from "next/navigation";import Link from "next/link";import {createClient} from "@/lib/supabase-browser";import {Status} from "@/lib/types";
const labels:Record<Status,string>={current:"მიმდინარე",shipping:"გზაში",delivered:"ჩაბარებული",cancelled:"გაუქმებული",return_pending:"უნდა დაბრუნდეს",returned:"დაბრუნდა",exchange:"გადასაცვლელია"};
export default function OrderPage(){const id=String(useParams().id),router=useRouter();const [o,setO]=useState<any>(null),[items,setItems]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[role,setRole]=useState("operator"),[status,setStatus]=useState<Status>("current"),[tracking,setTracking]=useState(""),[message,setMessage]=useState(""),[selected,setSelected]=useState("");
async function load(){const c=createClient();const {data:u}=await c.auth.getUser();if(u.user){const {data:p}=await c.from("profiles").select("role").eq("id",u.user.id).single();setRole(p?.role||"operator")}const {data}=await c.from("orders").select("*,profiles(full_name)").eq("id",id).single();const {data:it}=await c.from("order_items").select("*").eq("order_id",id).order("id");const {data:pr}=await c.from("products").select("*").eq("active",true).order("name");setO(data);setItems(it||[]);setProducts(pr||[]);setStatus((data?.status||"current") as Status);setTracking(data?.tracking_code||"")}
useEffect(()=>{load()},[id]);
async function saveBasic(){const c=createClient();const {data:u}=await c.auth.getUser();const old=o.status;const patch:any={status,tracking_code:tracking.trim()||null};if(role==="admin"){patch.customer_name=o.customer_name;patch.customer_phone=o.customer_phone;patch.customer_address=o.customer_address;patch.customer_comment=o.customer_comment;patch.delivery_fee=Number(o.delivery_fee||0);patch.discount=Number(o.discount||0);patch.subtotal=items.reduce((s,i)=>s+Number(i.unit_price)*Number(i.quantity),0);patch.total=Math.max(0,patch.subtotal+patch.delivery_fee-patch.discount)}const {error}=await c.from("orders").update(patch).eq("id",id);if(error){setMessage(error.message);return}if(old!==status)await c.from("order_status_history").insert({order_id:id,new_status:status,changed_by:u.user?.id});setMessage("ცვლილებები შენახულია.");load()}
async function updateItem(item:any){if(role!=="admin")return;await createClient().from("order_items").update({quantity:Number(item.quantity),unit_price:Number(item.unit_price)}).eq("id",item.id);await recalc()}
async function removeItem(itemId:string){if(role!=="admin"||!confirm("წავშალოთ პროდუქტი შეკვეთიდან?"))return;await createClient().from("order_items").delete().eq("id",itemId);await recalc()}
async function addItem(){if(role!=="admin"||!selected)return;const p=products.find(x=>x.id===selected);await createClient().from("order_items").insert({order_id:id,product_id:p.id,product_name:p.name,quantity:1,unit_price:p.price});setSelected("");await recalc()}
async function recalc(){const c=createClient();const {data:it}=await c.from("order_items").select("*").eq("order_id",id);const sub=(it||[]).reduce((s:any,i:any)=>s+Number(i.unit_price)*Number(i.quantity),0);await c.from("orders").update({subtotal:sub,total:Math.max(0,sub+Number(o.delivery_fee||0)-Number(o.discount||0))}).eq("id",id);load()}
async function deleteOrder(){if(role!=="admin"||!confirm("ნამდვილად წავშალოთ შეკვეთა? ეს მოქმედება შეუქცევადია."))return;const c=createClient();await c.from("order_status_history").delete().eq("order_id",id);await c.from("order_items").delete().eq("order_id",id);const {error}=await c.from("orders").delete().eq("id",id);if(error){setMessage(error.message);return}router.push("/dashboard")}
if(!o)return <p>იტვირთება...</p>;return <><div className="top"><div><div className="title">შეკვეთა #{o.order_number}</div><div className="muted">{role==="admin"?"Admin — სრული რედაქტირება":"Operator — მხოლოდ სტატუსი და თრექინგი"}</div></div><Link className="btn secondary" href="/dashboard">← უკან</Link></div>{message&&<div className="success-box">{message}</div>}
<div className="grid2"><div className="panel"><h3>მომხმარებელი</h3>{[["სახელი","customer_name"],["ტელეფონი","customer_phone"],["მისამართი","customer_address"]].map(([l,k])=><div className="field" key={k}><label>{l}</label><input disabled={role!=="admin"} value={o[k]||""} onChange={e=>setO({...o,[k]:e.target.value})}/></div>)}<div className="field"><label>კომენტარი</label><textarea disabled={role!=="admin"} value={o.customer_comment||""} onChange={e=>setO({...o,customer_comment:e.target.value})}/></div></div>
<div className="panel"><h3>მართვა</h3><div className="field"><label>სტატუსი</label><select value={status} onChange={e=>setStatus(e.target.value as Status)}>{(Object.keys(labels) as Status[]).map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></div><div className="field"><label>თრექინგ კოდი</label><input value={tracking} onChange={e=>setTracking(e.target.value)}/></div>{role==="admin"&&<><div className="field"><label>მიტანის საფასური (₾)</label><input type="number" value={o.delivery_fee||0} onChange={e=>setO({...o,delivery_fee:Number(e.target.value)})}/></div><div className="field"><label>ფასდაკლება (₾)</label><input type="number" value={o.discount||0} onChange={e=>setO({...o,discount:Number(e.target.value)})}/></div></>}<button className="btn" onClick={saveBasic}>ცვლილებების შენახვა</button></div></div>
<div className="panel"><h3>პროდუქტები</h3>{role==="admin"&&<div className="row" style={{marginBottom:14}}><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">პროდუქტის დამატება...</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} — {p.price} ₾</option>)}</select><button className="btn" onClick={addItem}>დამატება</button></div>}<table className="table"><thead><tr><th>პროდუქტი</th><th>რაოდენობა</th><th>ფასი</th><th>ჯამი</th>{role==="admin"&&<th></th>}</tr></thead><tbody>{items.map((i,idx)=><tr key={i.id}><td>{i.product_name}</td><td>{role==="admin"?<input className="mini-input" type="number" min="1" value={i.quantity} onChange={e=>setItems(x=>x.map((a,n)=>n===idx?{...a,quantity:Number(e.target.value)}:a))}/>:i.quantity}</td><td>{role==="admin"?<input className="mini-input" type="number" step="0.01" value={i.unit_price} onChange={e=>setItems(x=>x.map((a,n)=>n===idx?{...a,unit_price:Number(e.target.value)}:a))}/>:Number(i.unit_price).toFixed(2)+" ₾"}</td><td>{(Number(i.unit_price)*Number(i.quantity)).toFixed(2)} ₾</td>{role==="admin"&&<td><button className="btn secondary" onClick={()=>updateItem(i)}>შენახვა</button> <button className="btn danger" onClick={()=>removeItem(i.id)}>წაშლა</button></td>}</tr>)}</tbody></table><p>პროდუქტები: <b>{Number(o.subtotal||0).toFixed(2)} ₾</b> · მიტანა: <b>{Number(o.delivery_fee||0).toFixed(2)} ₾</b> · ფასდაკლება: <b>{Number(o.discount||0).toFixed(2)} ₾</b></p><h2>სულ: {Number(o.total||0).toFixed(2)} ₾</h2></div>{role==="admin"&&<div className="panel danger-zone"><h3>Admin მოქმედება</h3><button className="btn danger" onClick={deleteOrder}>შეკვეთის წაშლა</button></div>}</>}
