"use client";
import {useEffect,useMemo,useState} from "react";import {useRouter} from "next/navigation";import {createClient} from "@/lib/supabase-browser";import {readAllRows} from "@/lib/paged-read";import {Product,ProductVariant} from "@/lib/types";
type Item={product:Product,variant:ProductVariant|null,quantity:number,price:number,weight:number};
type Region={id:number,name:string};
import {quoteUnitWeight, quoteTotalWeight} from "@/lib/onway-quote";
import {useOnwayQuote} from "./useOnwayQuote";
import { DeliveryMethod, canEditOrders, deliveryMethods, isDeliveryMethod, parseDeliveryFee } from "@/lib/order-options";
export default function NewOrder(){const [products,setProducts]=useState<Product[]>([]),[variants,setVariants]=useState<ProductVariant[]>([]),[items,setItems]=useState<Item[]>([]),[selected,setSelected]=useState(""),[selectedVariant,setSelectedVariant]=useState(""),[qtyText,setQtyText]=useState("1"),[productSearch,setProductSearch]=useState(""),[productOpen,setProductOpen]=useState(false),[customer,setCustomer]=useState({name:"",phone:"",city:"",address:"",comment:""}),[paymentType,setPaymentType]=useState<"cod"|"prepaid">("cod"),[delivery,setDelivery]=useState(""),[discount,setDiscount]=useState(""),[error,setError]=useState(""),[warning,setWarning]=useState(""),[regions,setRegions]=useState<Region[]>([]),[citySearch,setCitySearch]=useState(""),[cityOpen,setCityOpen]=useState(false),[regionsError,setRegionsError]=useState("");const router=useRouter();const [deliveryMethod,setDeliveryMethod]=useState<DeliveryMethod>("onway"),[canCreate,setCanCreate]=useState(false);
useEffect(()=>{fetch("/api/onway/regions",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setRegions(d.regions||[])}).catch(e=>setRegionsError(e?.message||"OnWay-ის ქალაქების სია ვერ ჩაიტვირთა."));const c=createClient();Promise.all([readAllRows<Product>(c,"products",true),readAllRows<ProductVariant>(c,"product_variants",true)]).then(([p,v])=>{setProducts(p);setVariants(v)}).catch(()=>{})},[]);
useEffect(()=>{let cancelled=false;(async()=>{const c=createClient();const {data:{user}}=await c.auth.getUser();if(!user){router.replace("/login");return}const {data:profile}=await c.from("profiles").select("role,active").eq("id",user.id).single();if(!profile||profile.active!==true||!canEditOrders(profile.role)){router.replace("/dashboard");return}if(!cancelled)setCanCreate(true)})();return()=>{cancelled=true}},[router]);
const available=useMemo(()=>variants.filter(v=>v.product_id===selected),[variants,selected]);
const productResults=useMemo(()=>{const norm=(t:string)=>t.normalize("NFC").toLocaleLowerCase("ka-GE").trim(),q=norm(productSearch);if(!q)return products.slice(0,50).map(p=>({product:p,variantId:"",label:p.name}));const out:{product:Product,variantId:string,label:string}[]=[];for(const p of products){const productHit=norm(p.name).includes(q)||norm(p.sku||"").includes(q);if(productHit){out.push({product:p,variantId:"",label:p.name});continue}for(const v of variants){if(v.product_id!==p.id)continue;if(norm(p.name+" "+v.name).includes(q)||norm(v.sku||"").includes(q))out.push({product:p,variantId:v.id,label:p.name+" — "+v.name})}if(out.length>=50)break}return out.slice(0,50)},[products,variants,productSearch]);
const filteredRegions=useMemo(()=>{const q=citySearch.trim().toLocaleLowerCase("ka-GE");return (q?regions.filter(r=>r.name.toLocaleLowerCase("ka-GE").includes(q)):regions).slice(0,30)},[regions,citySearch]);
function chooseCity(r:Region){setCustomer({...customer,city:r.name,cityId:r.id} as any);setCitySearch(r.name);setCityOpen(false)}const subtotal=items.reduce((s,i)=>s+i.price*i.quantity,0),packageWeight=items.reduce((s,i)=>s+i.weight*i.quantity,0),total=Math.max(0,subtotal+Number(delivery||0)-Number(discount||0));
const quoteWeight=quoteTotalWeight(items);
const quoteDestination=regions.find(r=>r.id===(customer as any).cityId)?.id??null;
const quoteItemKey=JSON.stringify(items.map(i=>[i.product.id,i.variant?.id??null,i.quantity,i.product.weight_kg,i.variant?.weight_kg]));
const quote=useOnwayQuote({enabled:canCreate&&deliveryMethod==="onway",destination:quoteDestination,weight:quoteWeight,itemKey:quoteItemKey,onQuote:setDelivery});
function chooseProduct(id:string){setSelected(id);setSelectedVariant("")}
function pickResult(r:{product:Product,variantId:string,label:string}){setSelected(r.product.id);setSelectedVariant(r.variantId);setProductSearch(r.label);setProductOpen(false)}
// Keep the existing order-snapshot fallback for legacy catalog rows. Quotes use
// raw catalog weights above and never use this fallback; missing weight does not block creation.
function add(){const qty=Math.max(1,Math.floor(Number(qtyText))||1);const p=products.find(x=>x.id===selected);if(!p)return;if(available.length&&!selectedVariant){setError("ამ პროდუქტისთვის აირჩიე ვარიანტი.");return}const v=available.find(x=>x.id===selectedVariant)||null,price=v?Number(v.price):Number(p.price),weight=quoteUnitWeight(p,v)??1,key=p.id+":"+(v?.id||"base");setItems(x=>{const old=x.find(i=>i.product.id+":"+(i.variant?.id||"base")===key);if(old)return x.map(i=>i.product.id+":"+(i.variant?.id||"base")===key?{...i,quantity:i.quantity+qty}:i);return[...x,{product:p,variant:v,quantity:qty,price,weight}]});setSelected("");setSelectedVariant("");setProductSearch("");setQtyText("1");setError("")}
async function checkDuplicates(){const phone=customer.phone.trim(),address=customer.address.trim();if(!phone&&!address){setWarning("");return}try{const {data,error}=await createClient().rpc("check_order_duplicates",{p_phone:phone||null,p_address:address||null});if(error)throw error;const rows=(data||[]) as any[];setWarning(rows.length?"⚠️ "+rows.slice(0,5).map(r=>`${r.match_type==="phone"?"ტელეფონი":"მისამართი"} უკვე გვხვდება შეკვეთაში #${r.order_number} — ${new Date(r.created_at).toLocaleDateString("ka-GE")}`).join("\n"):"")}catch{setWarning("დუბლიკატის შემოწმება ვერ მოხერხდა. შეკვეთის შექმნა მაინც შეგიძლია.")}}
async function save(){if(!canCreate)return;setError("");if(!isDeliveryMethod(deliveryMethod)||parseDeliveryFee(delivery||0)===null){setError("აირჩიეთ მიწოდების მეთოდი და მიუთითეთ არაუარყოფითი მიტანის საფასური.");return}if(!customer.name.trim()||!customer.phone.trim()||!(customer as any).cityId||!customer.city.trim()||!customer.address.trim()||!items.length){setError("შეავსე მომხმარებლის სახელი, ტელეფონი, ქალაქი/რეგიონი, მისამართი და დაამატე პროდუქტი.");return}try{const c=createClient(),{data:user,error:authError}=await c.auth.getUser();if(authError||!user.user){setError("სესია დასრულებულია. თავიდან შედი სისტემაში.");return}const {data:profile,error:profileError}=await c.from("profiles").select("role,active").eq("id",user.user.id).single();if(profileError||!profile||profile.active!==true||!canEditOrders(profile.role)){setError("შეკვეთის შექმნის უფლება არ გაქვთ.");return}const {data:order,error:e}=await c.from("orders").insert({customer_name:customer.name.trim(),customer_phone:customer.phone.trim(),customer_city:customer.city.trim(),customer_city_id:(customer as any).cityId,customer_address:customer.address.trim(),customer_comment:customer.comment.trim(),payment_type:paymentType,delivery_method:deliveryMethod,package_weight:packageWeight,subtotal,delivery_fee:Number(delivery||0),discount:Number(discount||0),total,created_by:user.user.id,status:"current"}).select().single();if(e||!order){setError(e?.code==="23505"?"შეკვეთის ნომერი უკვე არსებობს. სცადე ხელახლა.":(e?.message||"შეკვეთა ვერ შეიქმნა."));return}const {error:ie}=await c.from("order_items").insert(items.map(i=>({order_id:order.id,product_id:i.product.id,product_name:i.product.name,variant_id:i.variant?.id||null,variant_name:i.variant?.name||null,quantity:i.quantity,unit_price:i.price,weight_kg:i.weight})));if(ie){setError("შეკვეთა შეიქმნა, მაგრამ პროდუქტები ვერ დაემატა: "+ie.message);return}router.push(`/orders/${order.id}`)}catch{setError("შეკვეთა ვერ შეიქმნა. შეამოწმე ინტერნეტი და სცადე ხელახლა.")}}
if(!canCreate)return <p>იტვირთება...</p>;return <><div className="top"><div><div className="title">ახალი შეკვეთა</div></div></div>{error&&<div className="error">{error}</div>}{warning&&<div className="warning-box" style={{whiteSpace:"pre-line"}}>{warning}</div>}<div className="panel"><h3>მომხმარებელი</h3><div className="grid2"><div className="field"><label>სახელი და გვარი</label><input value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/></div><div className="field"><label>ტელეფონი</label><input value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})} onBlur={checkDuplicates}/></div><div className="field" style={{position:"relative"}}><label>ქალაქი / რეგიონი</label><input value={citySearch} onFocus={()=>setCityOpen(true)} onChange={e=>{setCitySearch(e.target.value);setCustomer({...customer,city:"",cityId:null} as any);setCityOpen(true)}} placeholder="მოძებნე OnWay-ის ქალაქი / რეგიონი..." autoComplete="off"/>{regionsError&&<div className="error" style={{marginTop:6}}>{regionsError}</div>}{cityOpen&&filteredRegions.length>0&&<div style={{position:"absolute",zIndex:30,left:0,right:0,top:"100%",maxHeight:260,overflowY:"auto",background:"#fff",border:"1px solid #dfe3ea",borderRadius:10,boxShadow:"0 10px 30px rgba(0,0,0,.12)"}}>{filteredRegions.map(r=><button type="button" key={r.id} onMouseDown={e=>e.preventDefault()} onClick={()=>chooseCity(r)} style={{display:"block",width:"100%",textAlign:"left",padding:"10px 12px",border:0,borderBottom:"1px solid #eee",background:"#fff",cursor:"pointer"}}>{r.name}</button>)}</div>}</div><div className="field"><label>მისამართი</label><input value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})} onBlur={checkDuplicates}/></div><div className="field"><label>მიწოდების მეთოდი</label><select required value={deliveryMethod} onChange={e=>setDeliveryMethod(e.target.value as DeliveryMethod)}>{Object.entries(deliveryMethods).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><div className="field"><label>გადახდის ტიპი</label><select value={paymentType} onChange={e=>setPaymentType(e.target.value as "cod"|"prepaid")}><option value="cod">კურიერთან გადახდა (COD)</option><option value="prepaid">წინასწარ გადახდილი</option></select></div><div className="field"><label>კომენტარი</label><textarea value={customer.comment} onChange={e=>setCustomer({...customer,comment:e.target.value})}/></div></div></div>
<div className="panel"><h3>პროდუქტები</h3><div className="formline"><div className="field" style={{position:"relative"}}><label>პროდუქტი</label><input value={productSearch} placeholder="მოძებნე სახელით ან ბარკოდით..." autoComplete="off" inputMode="search" onFocus={()=>setProductOpen(true)} onBlur={()=>setTimeout(()=>setProductOpen(false),200)} onChange={e=>{setProductSearch(e.target.value);setSelected("");setSelectedVariant("");setProductOpen(true)}} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();if(productResults.length===1)pickResult(productResults[0])}}}/>{productOpen&&!selected&&<div style={{position:"absolute",zIndex:30,left:0,right:0,top:"100%",maxHeight:260,overflowY:"auto",background:"#fff",border:"1px solid #dfe3ea",borderRadius:10,boxShadow:"0 10px 30px rgba(0,0,0,.12)"}}>{productResults.length?productResults.map(r=><button type="button" key={r.product.id+":"+r.variantId} onMouseDown={e=>e.preventDefault()} onClick={()=>pickResult(r)} style={{display:"block",width:"100%",textAlign:"left",padding:"10px 12px",border:0,borderBottom:"1px solid #eee",background:"#fff",cursor:"pointer"}}>{r.label}</button>):<div style={{padding:"10px 12px"}}>ვერაფერი მოიძებნა</div>}</div>}</div>{selected&&available.length>0&&<div className="field"><label>ვარიანტი</label><select value={selectedVariant} onChange={e=>setSelectedVariant(e.target.value)}><option value="">აირჩიე ვარიანტი</option>{available.map(v=><option key={v.id} value={v.id}>{v.name} — {Number(v.price).toFixed(2)} ₾</option>)}</select></div>}<div className="field"><label>რაოდენობა</label><input type="text" inputMode="numeric" pattern="[0-9]*" value={qtyText} onFocus={e=>e.target.select()} onChange={e=>setQtyText(e.target.value.replace(/\D/g,"").slice(0,4))} onBlur={()=>setQtyText(String(Math.max(1,Number(qtyText)||1)))}/></div><button className="btn" onClick={add}>დამატება</button></div><table className="table"><thead><tr><th>პროდუქტი</th><th>ვარიანტი</th><th>რაოდ.</th><th>ფასი</th><th>წონა</th><th></th></tr></thead><tbody>{items.map(i=>{const key=i.product.id+":"+(i.variant?.id||"base");return <tr key={key}><td>{i.product.name}</td><td>{i.variant?.name||"—"}</td><td>{i.quantity}</td><td>{i.price.toFixed(2)} ₾</td><td>{quoteUnitWeight(i.product,i.variant)===null?"წონა მიუთითეთ":(quoteUnitWeight(i.product,i.variant)!*i.quantity).toFixed(2)+" კგ"}</td><td><button className="btn danger" onClick={()=>setItems(x=>x.filter(a=>a.product.id+":"+(a.variant?.id||"base")!==key))}>წაშლა</button></td></tr>})}</tbody></table><p>ამანათის საერთო წონა: <b>{!items.length?"—":quoteWeight===null?"წონა მიუთითეთ":quoteWeight.toFixed(2)+" კგ"}</b></p></div>
<div className="panel"><div className="grid2"><div>{deliveryMethod==="onway"&&<div role="status" aria-live="polite" style={{marginBottom:12}}>{!quoteDestination?<p>ავტომატური ფასისთვის აირჩიეთ ქალაქი OnWay-ის სიიდან. მიტანის საფასურის ხელით მითითება შესაძლებელია.</p>:!items.length?<p>OnWay-ის ფასისთვის დაამატეთ პროდუქტები.</p>:quoteWeight===null?<p>პროდუქტის/ვარიანტის სწორი წონა მითითებული არ არის; ავტომატური ფასი ვერ გამოითვლება. მიტანის საფასური მიუთითეთ ხელით.</p>:quote.loading?<p>OnWay-ის ფასი იტვირთება...</p>:quote.error?<p>{quote.error}</p>:quote.price!==null?<p>OnWay-ის ფასი: <b>{quote.price.toFixed(2)} ₾</b></p>:null}</div>}<div className="field"><label>მიტანის საფასური (₾)</label><input type="number" min="0" step="0.01" value={delivery} placeholder="0" onChange={e=>setDelivery(e.target.value)}/></div><div className="field"><label>ფასდაკლება (₾)</label><input type="number" min="0" step="0.01" value={discount} placeholder="0" onChange={e=>setDiscount(e.target.value)}/></div></div><div><p>პროდუქტები: <b>{subtotal.toFixed(2)} ₾</b></p><p>მიტანა: <b>{Number(delivery||0).toFixed(2)} ₾</b></p><p>ფასდაკლება: <b>{Number(discount||0).toFixed(2)} ₾</b></p><h2>სულ: {total.toFixed(2)} ₾</h2><button className="btn" onClick={save}>შეკვეთის შენახვა</button></div></div></div></>}
