"use client";
import ExcelImport from "./ExcelImport";
import {useEffect,useMemo,useState} from "react";import {createClient} from "@/lib/supabase-browser";
export default function Products(){const [items,setItems]=useState<any[]>([]),[variants,setVariants]=useState<any[]>([]),[role,setRole]=useState("operator");const [name,setName]=useState(""),[price,setPrice]=useState(0),[sku,setSku]=useState(""),[weight,setWeight]=useState("1"),[search,setSearch]=useState("");const [open,setOpen]=useState<string|null>(null),[vname,setVname]=useState(""),[vprice,setVprice]=useState(0),[vsku,setVsku]=useState(""),[vweight,setVweight]=useState("");const [message,setMessage]=useState("");
const filteredItems=useMemo(()=>{const q=search.trim().toLowerCase();return !q?items:items.filter(p=>(p.name||"").toLowerCase().includes(q));},[items,search]);
async function load(){const c=createClient();const {data:u}=await c.auth.getUser();if(u.user){const {data:p}=await c.from("profiles").select("role").eq("id",u.user.id).single();setRole(p?.role||"operator")}const [{data,error},{data:v,error:ve}]=await Promise.all([c.from("products").select("*").order("name"),c.from("product_variants").select("*").order("name")]);if(error||ve)setMessage("პროდუქტების ჩატვირთვა ვერ მოხერხდა.");setItems(data||[]);setVariants(v||[])}useEffect(()=>{load()},[]);
async function add(){if(role!=="admin"||!name.trim())return;const w=Number(weight);if(!w||w<=0){setMessage("მიუთითე პროდუქტის წონა.");return}const {error}=await createClient().from("products").insert({name:name.trim(),price:Number(price),sku:sku||null,weight_kg:w,active:true});if(error){setMessage("პროდუქტი ვერ დაემატა: "+error.message);return}setName("");setPrice(0);setSku("");setWeight("1");setMessage("პროდუქტი დაემატა.");load()}
async function updateProduct(p:any,patch:any){if(role!=="admin")return;const {error}=await createClient().from("products").update(patch).eq("id",p.id);if(error){setMessage("ცვლილება ვერ შეინახა: "+error.message);return}load()}
async function addVariant(product:any){if(role!=="admin"||!vname.trim())return;const {error}=await createClient().from("product_variants").insert({product_id:product.id,name:vname.trim(),price:Number(vprice),sku:vsku||null,weight_kg:vweight===""?null:Number(vweight),active:true});if(error){setMessage("ვარიანტი ვერ დაემატა: "+error.message);return}setVname("");setVprice(Number(product.price));setVsku("");setVweight("");load()}
async function toggleVariant(v:any){const {error}=await createClient().from("product_variants").update({active:!v.active}).eq("id",v.id);if(error)setMessage("ცვლილება ვერ შეინახა: "+error.message);else load()}
async function deleteVariant(v:any){if(!confirm(`წავშალოთ ვარიანტი "${v.name}"?`))return;const {error}=await createClient().from("product_variants").delete().eq("id",v.id);if(error)setMessage("ვარიანტი ვერ წაიშალა: "+error.message);else load()}
return <><div className="top"><div><div className="title">პროდუქტები</div><div className="muted">წონა გამოიყენება OnWay-ში გაგზავნისას</div></div></div>{message&&<div className="success-box">{message}</div>}{role==="admin"&&<ExcelImport onImported={load}/>}{role==="admin"&&<div className="panel"><h3>პროდუქტის დამატება</h3><div className="formline"><div className="field"><label>დასახელება</label><input value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>ფასი</label><input type="number" value={price} onChange={e=>setPrice(Number(e.target.value))}/></div><div className="field"><label>კოდი</label><input value={sku} onChange={e=>setSku(e.target.value)}/></div><div className="field"><label>წონა (კგ)</label><input type="number" min="0.01" step="0.01" value={weight} onChange={e=>setWeight(e.target.value)}/></div><button className="btn" onClick={add}>დამატება</button></div></div>}
<div className="panel"><div className="field" style={{marginBottom:12}}><label>პროდუქტის ძებნა</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ჩაწერე პროდუქტის სახელი..."/></div><table className="table"><thead><tr><th>დასახელება</th><th>კოდი</th><th>ფასი</th><th>წონა</th><th>ვარიანტები</th><th>სტატუსი</th>{role==="admin"&&<th></th>}</tr></thead><tbody>{filteredItems.map(p=>{const vs=variants.filter(v=>v.product_id===p.id);return <><tr key={p.id}><td><b>{p.name}</b></td><td>{p.sku||"—"}</td><td>{Number(p.price).toFixed(2)} ₾</td><td>{role==="admin"?<input className="mini-input" type="number" min="0.01" step="0.01" value={p.weight_kg??1} onChange={e=>setItems(x=>x.map(a=>a.id===p.id?{...a,weight_kg:e.target.value}:a))} onBlur={()=>updateProduct(p,{weight_kg:Number(p.weight_kg)||1})}/>:Number(p.weight_kg||1).toFixed(2)+" კგ"}</td><td>{vs.length?<button className="variant-count" onClick={()=>setOpen(open===p.id?null:p.id)}>{vs.length} ვარიანტი</button>:role==="admin"?<button className="variant-count" onClick={()=>{setOpen(p.id);setVprice(Number(p.price))}}>+ ვარიანტი</button>:"—"}</td><td>{p.active?"აქტიური":"არააქტიური"}</td>{role==="admin"&&<td><button className="btn secondary" onClick={()=>updateProduct(p,{active:!p.active})}>{p.active?"გახადე არააქტიური":"გააქტიურე"}</button></td>}</tr>{open===p.id&&<tr key={p.id+"-variants"}><td colSpan={7}><div className="variant-box"><h4>{p.name} — ვარიანტები</h4>{vs.map(v=><div className="variant-row" key={v.id}><span><b>{v.name}</b>{v.sku?` · ${v.sku}`:""}</span><span>{Number(v.price).toFixed(2)} ₾</span><span>{v.weight_kg?`${Number(v.weight_kg).toFixed(2)} კგ`:"საბაზისო წონა"}</span><span>{v.active?"აქტიური":"არააქტიური"}</span>{role==="admin"&&<span><button className="btn secondary" onClick={()=>toggleVariant(v)}>{v.active?"გამორთვა":"ჩართვა"}</button> <button className="btn danger" onClick={()=>deleteVariant(v)}>წაშლა</button></span>}</div>)}{role==="admin"&&<div className="variant-add"><input placeholder="მაგ. Honda" value={vname} onChange={e=>setVname(e.target.value)}/><input placeholder="კოდი" value={vsku} onChange={e=>setVsku(e.target.value)}/><input type="number" placeholder="ფასი" value={vprice} onChange={e=>setVprice(Number(e.target.value))}/><input type="number" min="0.01" step="0.01" placeholder="წონა (ცარიელი = საბაზისო)" value={vweight} onChange={e=>setVweight(e.target.value)}/><button className="btn" onClick={()=>addVariant(p)}>ვარიანტის დამატება</button></div>}</div></td></tr>}</>})}</tbody></table></div></>}
