"use client";
import {useEffect,useState} from "react";import {createClient} from "@/lib/supabase-browser";
export default function Products(){const [items,setItems]=useState<any[]>([]),[variants,setVariants]=useState<any[]>([]),[role,setRole]=useState("operator");const [name,setName]=useState(""),[price,setPrice]=useState(0),[sku,setSku]=useState("");const [open,setOpen]=useState<string|null>(null),[vname,setVname]=useState(""),[vprice,setVprice]=useState(0),[vsku,setVsku]=useState("");
async function load(){const c=createClient();const {data:u}=await c.auth.getUser();if(u.user){const {data:p}=await c.from("profiles").select("role").eq("id",u.user.id).single();setRole(p?.role||"operator")}const [{data},{data:v}]=await Promise.all([c.from("products").select("*").order("name"),c.from("product_variants").select("*").order("name")]);setItems(data||[]);setVariants(v||[])}useEffect(()=>{load()},[]);
async function add(){if(role!=="admin"||!name.trim())return;await createClient().from("products").insert({name,price:Number(price),sku:sku||null,active:true});setName("");setPrice(0);setSku("");load()}
async function toggle(p:any){if(role!=="admin")return;await createClient().from("products").update({active:!p.active}).eq("id",p.id);load()}
async function addVariant(product:any){if(role!=="admin"||!vname.trim())return;const {error}=await createClient().from("product_variants").insert({product_id:product.id,name:vname.trim(),price:Number(vprice),sku:vsku||null,active:true});if(error){alert(error.message);return}setVname("");setVprice(Number(product.price));setVsku("");load()}
async function toggleVariant(v:any){await createClient().from("product_variants").update({active:!v.active}).eq("id",v.id);load()}
async function deleteVariant(v:any){if(!confirm(`წავშალოთ ვარიანტი "${v.name}"?`))return;const {error}=await createClient().from("product_variants").delete().eq("id",v.id);if(error)alert(error.message);load()}
return <><div className="top"><div><div className="title">პროდუქტები</div><div className="muted">პროდუქტს სურვილისამებრ შეიძლება ჰქონდეს ვარიანტები</div></div></div>{role==="admin"&&<div className="panel"><h3>პროდუქტის დამატება</h3><div className="formline"><div className="field"><label>დასახელება</label><input value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>საბაზისო ფასი</label><input type="number" value={price} onChange={e=>setPrice(Number(e.target.value))}/></div><div className="field"><label>კოდი</label><input value={sku} onChange={e=>setSku(e.target.value)}/></div><button className="btn" onClick={add}>დამატება</button></div></div>}
<div className="panel"><table className="table"><thead><tr><th>დასახელება</th><th>კოდი</th><th>ფასი</th><th>ვარიანტები</th><th>სტატუსი</th>{role==="admin"&&<th></th>}</tr></thead><tbody>{items.map(p=>{const vs=variants.filter(v=>v.product_id===p.id);return <><tr key={p.id}><td><b>{p.name}</b></td><td>{p.sku||"—"}</td><td>{Number(p.price).toFixed(2)} ₾</td><td>{vs.length?<button className="variant-count" onClick={()=>setOpen(open===p.id?null:p.id)}>{vs.length} ვარიანტი</button>:role==="admin"?<button className="variant-count" onClick={()=>{setOpen(p.id);setVprice(Number(p.price))}}>+ ვარიანტი</button>:"—"}</td><td>{p.active?"აქტიური":"არააქტიური"}</td>{role==="admin"&&<td><button className="btn secondary" onClick={()=>toggle(p)}>{p.active?"გახადე არააქტიური":"გააქტიურე"}</button></td>}</tr>
{open===p.id&&<tr key={p.id+"-variants"}><td colSpan={6}><div className="variant-box"><h4>{p.name} — ვარიანტები</h4>{vs.map(v=><div className="variant-row" key={v.id}><span><b>{v.name}</b>{v.sku?` · ${v.sku}`:""}</span><span>{Number(v.price).toFixed(2)} ₾</span><span>{v.active?"აქტიური":"არააქტიური"}</span>{role==="admin"&&<span><button className="btn secondary" onClick={()=>toggleVariant(v)}>{v.active?"გამორთვა":"ჩართვა"}</button> <button className="btn danger" onClick={()=>deleteVariant(v)}>წაშლა</button></span>}</div>)}{role==="admin"&&<div className="variant-add"><input placeholder="მაგ. Honda" value={vname} onChange={e=>setVname(e.target.value)}/><input placeholder="კოდი" value={vsku} onChange={e=>setVsku(e.target.value)}/><input type="number" placeholder="ფასი" value={vprice} onChange={e=>setVprice(Number(e.target.value))}/><button className="btn" onClick={()=>addVariant(p)}>ვარიანტის დამატება</button></div>}</div></td></tr>}</>})}</tbody></table></div></>}
